use_frameworks!

platform :ios, '9.0'

target 'LibIrmakFile_Example' do
  pod 'Countly'
  pod 'LibIrmakFile', :path => '../'

  target 'LibIrmakFile_Tests' do
    inherit! :search_paths

    
  end
end
